version: 1
updates:
  - package-ecosystem: "pip"  # Specify the package manager, e.g., pip for Python
    directory: "/"  # Location of your dependency files (e.g., / for requirements.txt)
    schedule:
      interval: "weekly"  # Can be "daily", "weekly", or "monthly"
  - package-ecosystem: "github-actions"  # For GitHub Actions workflows
    directory: ".github/workflows"  # Location of your workflow files
    schedule:
      interval: "weekly"
