name: Automatic Testing

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 30  # Set a longer timeout (e.g., 30 minutes)

        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            

            - name: Install dependencies
              run: |
                python -m venv venv  # Create a virtual environment
                source venv/bin/activate  # Activate the virtual environment
                python -m pip install --upgrade pip
                pip install -r requirements.txt  # Install dependencies in the virtual environment
                
            - name: Test with pytest
              run: |
                source venv/bin/activate  # Ensure the virtual environment is activated
                pytest ./tests
        
        