name: Deploy to Google Cloud Run


on:
  push:
    branches:
      - docker  # Adjust the branch as needed

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/60415379904/locations/global/workloadIdentityPools/pool-party/providers/github'
        service_account: 'nates-service-account@lsit-tutorapp.iam.gserviceaccount.com'

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: lsit-tutorapp
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      run: |
        gcloud builds submit --tag gcr.io/lsit-tutorapp/fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/lsit-tutorapp/fastapi-app \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GITLAB_CLIENT_ID=830223bc5b3f77464d6f6a8ed40c53f999f0283fca8f1e4c2ca39f5f0bb93262,GITLAB_CLIENT_SECRET=gloas-e907281d69a987b5bb00024c7da626f8495d13282def115a7caea73f3433a675,GITLAB_REDIRECT_URI=http://localhost:8000/auth/callback,GITLAB_BASE_URL=https://gitlab.com,GITLAB_API_URL=https://gitlab.com//oauth/userinfo,SECRET_KEY=DbFLXVLJVpoGJf0Fifai_2g-UlbWB4xfU1Ve8GIBHSg,TOKEN_EXPIRE_MINUTES=30,REFRESH_TOKEN_EXPIRE_DAYS=7,SESSION_EXPIRE_MINUTES=60,HTTPS_ENABLED=True
