name: Deploy to Google Cloud Run


on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/60415379904/locations/global/workloadIdentityPools/pool-party/providers/github'
        service_account: 'nates-service-account@lsit-tutorapp.iam.gserviceaccount.com'

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: lsit-tutorapp
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Run Terraform
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIAL: ${{ secrets.GCP_SA_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        gcloud builds submit --tag gcr.io/lsit-tutorapp/fastapi-app

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/lsit-tutorapp/fastapi-app:latest \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated
