name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Adjust this to your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Step 4: Lint with flake8
      - name: Lint with flake8
        run: flake8 tutoring_app/app  # Replace `your_project/` with your source directory
        continue-on-error: true

      # Step 5: Check formatting with black
      - name: Check formatting with black
        run: black --check tutoring_app/app/  # Replace `your_project/` with your source directory
        continue-on-error: true