name: Pip Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    pip-audit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: install
          run: python -m pip install .
        - uses: pypa/gh-action-pip-audit@v1.1.0
          with:
            inputs: requirements.txt
