name: Pip Audit

on:
  pull_request:
    branches:
      - main

jobs:
  pip-audit:
    name: Pip Audit
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6  # Replace with the Python version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run pip-audit using the official GitHub Action
      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          audit-type: all  # Options: all, installed, or specified