name: Pip Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pip-audit:
    steps:
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
